2021-11-15 22:33:27,174 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:33:27,174 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — [Errno 2] No such file or directory: '/dev/i2c-1'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 280, in __init__
    self.open(bus)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 310, in open
    self.fd = os.open(filepath, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-1'
2021-11-15 22:33:27,177 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:33:27,177 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:33:27,177 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:33:27,177 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:33:27,177 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:33:27,178 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:33:27,181 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:33:27,181 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:33:27,182 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:33:27,182 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:33:27,182 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:33:27,182 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:33:43,761 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:33:43,761 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — [Errno 2] No such file or directory: '/dev/i2c-1'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 280, in __init__
    self.open(bus)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 310, in open
    self.fd = os.open(filepath, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-1'
2021-11-15 22:33:43,763 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:33:43,763 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:33:43,764 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:33:43,764 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:33:43,764 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:33:43,764 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:33:43,765 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:33:43,765 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:33:43,765 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:33:43,765 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:33:43,766 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:33:43,766 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:21,051 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:37:21,052 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — [Errno 2] No such file or directory: '/dev/i2c-1'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 280, in __init__
    self.open(bus)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 310, in open
    self.fd = os.open(filepath, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-1'
2021-11-15 22:37:21,055 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:37:21,055 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:37:21,055 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:37:21,056 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:21,056 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:37:21,056 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:37:21,057 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:37:21,057 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:21,057 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:37:21,058 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:21,058 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:37:21,058 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:37,165 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:37:37,166 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — [Errno 2] No such file or directory: '/dev/i2c-1'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 280, in __init__
    self.open(bus)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 310, in open
    self.fd = os.open(filepath, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-1'
2021-11-15 22:37:37,168 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:37:37,168 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:37:37,168 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:37:37,168 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:37,169 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:37:37,169 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:37:37,169 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:37:37,170 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:37,170 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:37:37,170 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:37,170 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:37:37,170 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:42,961 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:37:42,962 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — [Errno 2] No such file or directory: '/dev/i2c-1'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 280, in __init__
    self.open(bus)
  File "/Users/steve/Desktop/Projects/stond/pi/env/lib/python3.7/site-packages/smbus2/smbus2.py", line 310, in open
    self.fd = os.open(filepath, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/i2c-1'
2021-11-15 22:37:42,963 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:37:42,963 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:37:42,963 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:37:42,963 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:42,964 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:37:42,964 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:37:42,964 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:37:42,965 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:42,965 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:37:42,965 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:37:42,965 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:37:42,965 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:39:21,776 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:39:21,776 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SMBus'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
AttributeError: module 'tests' has no attribute 'SMBus'
2021-11-15 22:39:21,777 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:39:21,777 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:39:21,777 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:39:21,778 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:39:21,778 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:39:21,778 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:39:21,778 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:39:21,779 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:39:21,779 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:39:21,779 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:39:21,779 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:39:21,780 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:43:19,842 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:43:19,843 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SMBus'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
AttributeError: module 'tests' has no attribute 'SMBus'
2021-11-15 22:43:19,844 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:43:19,844 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:43:19,844 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:43:19,845 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:43:19,845 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:43:19,845 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:43:19,846 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:43:19,846 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:43:19,846 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:43:19,846 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:43:19,847 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:43:19,847 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:43:55,276 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:43:55,276 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SMBus'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
AttributeError: module 'tests' has no attribute 'SMBus'
2021-11-15 22:43:55,277 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:43:55,277 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:43:55,278 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:43:55,278 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:43:55,278 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:43:55,278 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:43:55,279 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:43:55,279 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:43:55,279 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:43:55,279 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:43:55,279 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:43:55,279 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:45:39,100 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:45:39,100 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SMBus'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
AttributeError: module 'tests' has no attribute 'SMBus'
2021-11-15 22:45:39,101 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:45:39,101 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:45:39,101 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:45:39,101 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:45:39,101 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:45:39,101 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:45:39,102 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:45:39,102 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:45:39,103 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:45:39,103 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:45:39,103 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:45:39,103 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:46:25,483 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:46:25,483 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SMBus'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
AttributeError: module 'tests' has no attribute 'SMBus'
2021-11-15 22:46:25,484 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:46:25,484 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:46:25,484 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Level Sensor setup
2021-11-15 22:46:25,485 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 93, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:46:25,485 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:46:25,485 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:46:25,486 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Fan Actuator not working
2021-11-15 22:46:25,486 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 11, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:46:25,486 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Lights Actuator not working
2021-11-15 22:46:25,486 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 35, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:46:25,486 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Humidifier not working
2021-11-15 22:46:25,487 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'GPIO'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/controller.py", line 59, in __init__
    RPi.GPIO.setmode(RPi.GPIO.BCM)
AttributeError: module 'tests' has no attribute 'GPIO'
2021-11-15 22:48:18,339 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:48:18,340 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SMBus'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 33, in __init__
    self.bus = smbus2.SMBus(port)
AttributeError: module 'tests' has no attribute 'SMBus'
2021-11-15 22:48:18,341 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:48:18,342 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:48:18,343 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:48:18,343 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:48:50,403 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error while loading BME280 sensor
2021-11-15 22:48:50,403 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'load_calibration_params'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 34, in __init__
    self.calibration_params = bme280.load_calibration_params(self.bus, self.address)
AttributeError: module 'tests' has no attribute 'load_calibration_params'
2021-11-15 22:48:50,404 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:48:50,404 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:48:50,405 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:48:50,406 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:49:17,018 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:49:17,018 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:49:17,019 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:49:17,019 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SPI'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SPI'
2021-11-15 22:49:51,481 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:49:51,481 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:49:51,482 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:49:51,482 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'SCK'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 103, in __init__
    spi = busio.SPI(clock=board.SCK, MISO=board.MISO, MOSI=board.MOSI)
AttributeError: module 'tests' has no attribute 'SCK'
2021-11-15 22:50:12,170 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:50:12,171 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 22:50:12,172 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during PH Sensor setup
2021-11-15 22:50:12,172 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — module 'tests' has no attribute 'DigitalInOut'
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 104, in __init__
    cs = digitalio.DigitalInOut(board.D22)
AttributeError: module 'tests' has no attribute 'DigitalInOut'
2021-11-15 22:50:22,704 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Some error during Water Temp Sensor setup
2021-11-15 22:50:22,704 — /Users/steve/Desktop/Projects/stond/pi/system.log — ERROR — list index out of range
Traceback (most recent call last):
  File "/Users/steve/Desktop/Projects/stond/pi/sensors.py", line 84, in __init__
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range
2021-11-15 23:30:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:34:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:35:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:36:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:37:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:38:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:39:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:40:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:41:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:42:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:43:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:44:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:45:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:46:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
2021-11-15 23:47:00,000 — /Users/steve/Desktop/Projects/stond/pi/system.log — INFO — Send Data
